spring:
  datasource:
    url: jdbc:mysql://192.168.2.100:3306/jdbc
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
#    hikari:
#      schema:
#        -classpath:department.sql